language: bash

matrix:
  include:
    - dist: xenial
      os: linux
      sudo: required
    - dist: bionic
      os: linux
      sudo: required
    
deploy:
  provider: script
  script: sudo bash ret install rocm -y --nov
  script: sudo bash ret install tensorflow -y --nov
  on:
    branch: master
