language: bash
os:
  - linux
dist: xenial

sudo: required
deploy:
  provider: script
  script: sudo bash ret install rocm -y --nov
  script: sudo bash ret install tensorflow -y --nov
  on:
    branch: dev
