language: bash
os:
  - linux
 

sudo: required
deploy:
  provider: script
  script: bash ret install rocm
  script: bash ret install tensorflow
  script: bash ret build docker
  script: bash ret build singularity
  on:
    branch: dev
